;===============================================================;
;                                                               ;
;                                                               ;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗      ;
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗     ;
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝     ;
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗     ;
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║     ;
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝     ;
;                                                               ;
;                                                               ;
;   To learn more about how to configure Polybar                ;
;   go to https://github.com/polybar/polybar                    ;
;                                                               ;
;   The README contains a lot of information                    ;
;                                                               ;
;===============================================================;

[colors]
background = #c000
background-alt = #333
foreground = #1E1
primary = #FC0
secondary = #07F
alert = #F00
disabled = #59F

[bar/example]
monitor = ${env:MONITOR:}
width = 100%
height = 24pt
#radius = 6
bottom = true
; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #0000

padding-left = 0
padding-right = 1

module-margin = 1

separator =  %{F#C22}|%{F-}
#separator-foreground = ${colors.disabled}

font-0 = monospace;2
#font-0 = "JetBrainsMono Nerd Font:style=Regular:size=12;5:/home/lika/.local/share/fonts/JetBrainsMonoNerdFontMono-Bold.ttf"

modules-left = i3 low_battery
modules-right = battery filesystem cpu system-nvidia-smi memory wlan eth sink pulseaudio date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3
; override-redirect = true

[module/i3]
type = internal/i3

; Only show workspaces defined on the same output as the bar
pin-workspaces = false
; Sort the workspaces by index instead of the default
index-sort = true
; Set the scroll cycle direction
reverse-scroll = false

ws-icon-0 = 10;0
ws-icon-1 = 1;1
ws-icon-2 = 2;2
ws-icon-3 = 3;3
ws-icon-4 = 4;4
ws-icon-5 = 5;5
ws-icon-6 = 6;6
ws-icon-7 = 7;7
ws-icon-8 = 8;8
ws-icon-9 = 9;9
ws-icon-10 = 11;Z
ws-icon-11 = 12;X
ws-icon-12 = 13;C
ws-icon-13 = 14;T
ws-icon-14 = 15;Y
ws-icon-15 = 16;U
ws-icon-16 = 17;I
ws-icon-17 = 18;O
ws-icon-18 = 19;P

;label-focused = %icon%
label-focused = %icon%
label-focused-underline= #F00
label-focused-foreground = #F00
label-focused-background = #111
label-focused-padding = 1

label-unfocused = %icon%
label-unfocused-foreground = #F00
label-unfocused-padding = 1

label-visible = %icon%
label-visible-foreground = #F00
label-visible-padding = 1

label-urgent = %icon%
label-urgent-foreground = #F0A
label-urgent-padding = 1


[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/arch]
type = custom/text
format = <label>
format-background = #c000
format-foreground = #f00
format-padding = 0
label = "  A󰣇 " 
label-foreground = #ff0

[module/xworkspaces]
type = internal/xworkspaces

pin-workspaces = true
; blue: #549FEA
label-active = %{F#F00}%name%%{F-}
label-active-background = #111
label-active-underline= #F00
label-active-padding = 1

label-occupied = %{F#F00}%name%%{F-}
label-occupied-padding = 1

label-urgent = %{F#F00}%name%%{F-}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %{F#F00}%name%%{F-}
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/low_battery]
type = custom/script
exec = /home/lika/Skripty/get_low_battery.sh
format-foreground = ${colors.foreground}

[module/xwindow]
type = internal/xwindow
label = %{F#FF0}%title:0:42:...%%{F-}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

#label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-mounted = %{F#FC0}Disk:%{F-} %percentage_used%%


label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

#[module/xkeyboard]
#type = internal/xkeyboard
#blacklist-0 = num lock

#label-layout = %layout%
#label-layout-foreground = ${colors.primary}

#label-indicator-padding = 2
#label-indicator-margin = 1
#label-indicator-foreground = ${colors.background}
#label-indicator-background = ${colors.secondary}

[module/battery]
type = internal/battery
interval = 5
full-at = 100
low-at = 15
battery = BAT0
adapter = ADP0
poll-interval = 5
label-low = %{F#F00}BAT: %percentage%% !!%{F-}
label-charging = %{F#FC0}BAT:%{F-} %percentage%% %{F#0F0}++%{F-}
label-discharging = %{F#FC0}BAT:%{F-} %percentage%% %{F#F00}--%{F-}
label-full = %{F#FC0}BAT:%{F-} %{F#0FF}FULL%{F-}

#[module/warning]
#type = custom/script
#exec = /home/lika/Skripty/low_battery_warning.sh

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM: "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/system-nvidia-smi]
type = custom/script
exec = ~/Skripty/get-nvidia-smi.sh
interval = 5

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU: "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
#label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
label-disconnected = %{F#FC0}%ifname%%{F#59F} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
#label-connected = %{A1:nm-connection-editor & disown:} %{F#F0C674}%ifname%%{F-} %essid% %local_ip% %{A}
label-connected = %{F#FC0}%ifname%%{F-} %{F#F60}[%essid%]%{F-} %{F#F5F}%local_ip%%{F-} %{F#0FF}[%downspeed%]%{F-} %signal%% 

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#FC0}%ifname%%{F-} %{F#F5F}%local_ip%%{F-} %{F#0FF}[%downspeed%]%{F-}
#| %local_ip6%

[module/sink]
type = custom/script
exec = /home/lika/Skripty/get_audio.sh
format-foreground = ${colors.primary}

[module/pulseaudio]
type = internal/pulseaudio

#format-volume-prefix = "%{A1:pavucontrol & disown:}🔉 %{A}"
#format-volume-prefix = "VOL: "
#format-volume-prefix-foreground = ${colors.primary}
#format-volume = <label-volume>

label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/date]
type = internal/date
interval = 1

date = %Y-%m-%d %H:%M:%S
date-alt = %A %d.%m - %H:%M

label = %{F#F31}%date%%{F-}
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
